# Generated by Django 4.0.5 on 2022-06-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
    ]
